SELECT [Restaurant_Name]
      ,CAST([Meal_Release_Date] AS DATE) AS [Release_Date]
      ,[Meal]
      ,[Meal_Description]
      ,[Meal_Sides]
      ,[COST]
      ,[Quantity]
      ,[COST]* [Quantity] as  [Revenue]
      ,[Additional_Details_1]
      ,[Additional_Details_2]
      ,[Additional_Details_3]
      INTO[NEW_Master_REV]
  FROM [master].[dbo].[Restaurant_New_Master]

  SELECT * FROM [Restaurant_New_Mas]
